In [1]:
import pandas as pd

In [4]:
data = {
    'Date': ['Jan-1', 'Jan-1', 'Jan-1', 'Jan-2', 'Jan-2', 'Jan-2'],
    'User': ['Luffy', 'Zoro', 'Nami', 'Usopp', 'Sanji', 'Robin'],
    'Method': ['Cash', 'Cash', 'Card', 'Cash', 'Card', 'Card'],
    'Price': [100, 80, 400, 250, 150, 350],
}
df = pd.DataFrame(data)
df

    Date   User Method  Price
0  Jan-1  Luffy   Cash    100
1  Jan-1   Zoro   Cash     80
2  Jan-1   Nami   Card    400
3  Jan-2  Usopp   Cash    250
4  Jan-2  Sanji   Card    150
5  Jan-2  Robin   Card    350

In [6]:
df.pivot_table(values='Price', index=['Date', 'User'], columns=['Method'])

Method        Card   Cash
Date  User
Jan-1 Luffy    NaN  100.0
      Nami   400.0    NaN
      Zoro     NaN   80.0
Jan-2 Robin  350.0    NaN
      Sanji  150.0    NaN
      Usopp    NaN  250.0

In [9]:
pivod_df = df.pivot_table(values='Price', 
                          index=['Date', 'Method'], 
                          columns=['User'])
pivod_df

User          Luffy   Nami  Robin  Sanji  Usopp  Zoro
Date  Method
Jan-1 Card      NaN  400.0    NaN    NaN    NaN   NaN
      Cash    100.0    NaN    NaN    NaN    NaN  80.0
Jan-2 Card      NaN    NaN  350.0  150.0    NaN   NaN
      Cash      NaN    NaN    NaN    NaN  250.0   NaN

In [11]:
pivod_df.xs('Card', level='Method')

User   Luffy   Nami  Robin  Sanji  Usopp  Zoro
Date
Jan-1    NaN  400.0    NaN    NaN    NaN   NaN
Jan-2    NaN    NaN  350.0  150.0    NaN   NaN

In [12]:
pivod_df.xs('Jan-1')

User    Luffy   Nami  Robin  Sanji  Usopp  Zoro
Method
Card      NaN  400.0    NaN    NaN    NaN   NaN
Cash    100.0    NaN    NaN    NaN    NaN  80.0