In [1]:
import pandas as pd
import numpy as np

In [43]:
df_movies = pd.read_csv('../../../data/raw/lecture/tmdb_5000_movies.csv')
df_credits = pd.read_csv('../../../data/raw/lecture/tmdb_5000_credits.csv')

In [35]:
df_movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')

In [36]:
df_credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [44]:
df = df_movies.merge(df_credits, 
                left_on='id', right_on='movie_id', 
                suffixes=('_movies', '_credits'))
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [38]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_movies', 'vote_average',
       'vote_count', 'movie_id', 'title_credits', 'cast', 'crew'],
      dtype='str')

In [39]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989,57165.484281
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891,88694.614033
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,5.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000,9014.500000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000,14629.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000,58610.500000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000,459488.000000

In [45]:
df['budget'] = df['budget'].apply(lambda x: np.nan if x == 0 else x)
df['revenue'] = df['revenue'].apply(lambda x: np.nan if x == 0 else x)

In [47]:
len(df)

4803

In [49]:
df = df.dropna()
len(df)

1249

In [51]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,1.249000e+03,1249.000000,1249.000000,1.249000e+03,1249.000000,1249.000000,1249.000000,1249.000000
mean,5.381870e+07,59759.024019,41.121181,1.844782e+08,110.829464,6.363731,1552.073659,59759.024019
std,5.495661e+07,84827.158074,50.839995,2.528517e+08,19.080856,0.860655,1873.621431,84827.158074
min,7.000000e+03,11.000000,0.097913,4.600000e+01,63.000000,0.000000,0.000000,11.000000
25%,1.500000e+07,6171.000000,16.574756,3.167062e+07,97.000000,5.800000,360.000000,6171.000000
50%,3.500000e+07,22821.000000,29.913530,9.045001e+07,108.000000,6.400000,827.000000,22821.000000
75%,7.500000e+07,70981.000000,49.046956,2.249203e+08,122.000000,7.000000,1990.000000,70981.000000
max,3.800000e+08,376659.000000,875.581305,2.787965e+09,201.000000,8.400000,13752.000000,376659.000000

In [52]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_movies', 'vote_average',
       'vote_count', 'movie_id', 'title_credits', 'cast', 'crew'],
      dtype='str')

In [55]:
df['profit'] = df['revenue'] - df['budget']
df['profit']

0       2.550965e+09
1       6.610000e+08
2       6.356746e+08
3       8.349391e+08
4       2.413910e+07
            ...
4752    3.514980e+05
4758   -3.399104e+06
4772   -2.119200e+04
4773    3.124130e+06
4796    4.177600e+05
Name: profit, Length: 1249, dtype: float64

In [59]:
df.groupby('original_language')['profit'].max()

original_language
af    6.879971e+06
cn   -1.716233e+07
de    7.458488e+07
en    2.550965e+09
es    7.268254e+07
fa    7.200000e+05
fr    1.639220e+08
id    3.005187e+06
it    4.800000e+06
ja    2.599251e+08
ko    7.748964e+07
nb    6.596780e+05
nl   -3.469952e+06
no    1.184662e+06
pt    2.734177e+07
th    4.366630e+05
zh    4.747361e+07
Name: profit, dtype: float64

In [61]:
df.groupby('original_language')['id'].count()

original_language
af       1
cn       1
de       4
en    1213
es       5
fa       1
fr       6
id       2
it       1
ja       4
ko       2
nb       1
nl       1
no       1
pt       1
th       1
zh       4
Name: id, dtype: int64

In [68]:
sorted_by_profit_df = df.sort_values('profit', 
                                     ascending=False).reset_index(drop=True)
sorted_by_profit_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew,profit
0,237000000.0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2.550965e+09
1,200000000.0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,Released,Nothing on Earth could come between them.,Titanic,7.5,7562,597,Titanic,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de...",1.645034e+09
2,150000000.0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,Released,The park is open.,Jurassic World,6.5,8662,135397,Jurassic World,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...","[{""credit_id"": ""52fe4bf7c3a368484e1a0683"", ""de...",1.363529e+09
3,190000000.0,"[{""id"": 28, ""name"": ""Action""}]",http://www.furious7.com/,168259,"[{""id"": 830, ""name"": ""car race""}, {""id"": 3428,...",en,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,102.322217,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,Released,Vengeance Hits Home,Furious 7,7.3,4176,168259,Furious 7,"[{""cast_id"": 17, ""character"": ""Dominic Toretto...","[{""credit_id"": ""52fe4cc8c3a36847f823e699"", ""de...",1.316249e+09
4,220000000.0,"[{""id"": 878, ""name"": ""Science Fiction""}, {""id""...",http://marvel.com/avengers_movie/,24428,"[{""id"": 242, ""name"": ""new york""}, {""id"": 5539,...",en,The Avengers,When an unexpected enemy emerges and threatens...,144.448633,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,Released,Some assembly required.,The Avengers,7.4,11776,24428,The Avengers,"[{""cast_id"": 46, ""character"": ""Tony Stark / Ir...","[{""credit_id"": ""52fe4495c3a368484e02b1cf"", ""de...",1.299558e+09

In [69]:
len(sorted_by_profit_df)

1249

In [71]:
sorted_by_profit_df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id,profit
count,1.249000e+03,1249.000000,1249.000000,1.249000e+03,1249.000000,1249.000000,1249.000000,1249.000000,1.249000e+03
mean,5.381870e+07,59759.024019,41.121181,1.844782e+08,110.829464,6.363731,1552.073659,59759.024019,1.306595e+08
std,5.495661e+07,84827.158074,50.839995,2.528517e+08,19.080856,0.860655,1873.621431,84827.158074,2.162675e+08
min,7.000000e+03,11.000000,0.097913,4.600000e+01,63.000000,0.000000,0.000000,11.000000,-1.657101e+08
25%,1.500000e+07,6171.000000,16.574756,3.167062e+07,97.000000,5.800000,360.000000,6171.000000,6.072209e+06
50%,3.500000e+07,22821.000000,29.913530,9.045001e+07,108.000000,6.400000,827.000000,22821.000000,5.141739e+07
75%,7.500000e+07,70981.000000,49.046956,2.249203e+08,122.000000,7.000000,1990.000000,70981.000000,1.595647e+08
max,3.800000e+08,376659.000000,875.581305,2.787965e+09,201.000000,8.400000,13752.000000,376659.000000,2.550965e+09

In [2]:
df_movies = pd.read_csv('../../../data/raw/lecture/tmdb_5000_movies.csv')
df_credits = pd.read_csv('../../../data/raw/lecture/tmdb_5000_credits.csv')

In [81]:
print(df_movies.columns)
print(df_credits.columns)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='str')
Index(['movie_id', 'title', 'cast', 'crew'], dtype='str')

In [3]:
df = df_movies.merge(df_credits, 
                     left_on='id', right_on='movie_id', 
                     suffixes=('_movies', '_credits'))
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [4]:
df = df[~((df['budget'] == 0) | (df['revenue'] == 0))]
len(df)

3229

In [5]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id
count,3.229000e+03,3229.000000,3229.000000,3.229000e+03,3229.000000,3229.000000,3229.000000,3229.000000
mean,4.065444e+07,44780.705791,29.033689,1.212430e+08,110.724373,6.309353,977.287395,44780.705791
std,4.439674e+07,74609.434723,36.165730,1.863029e+08,20.965694,0.873891,1414.309577,74609.434723
min,1.000000e+00,5.000000,0.019984,5.000000e+00,41.000000,0.000000,0.000000,5.000000
25%,1.050000e+07,4958.000000,10.446722,1.700000e+07,96.000000,5.800000,178.000000,4958.000000
50%,2.500000e+07,11451.000000,20.410354,5.518472e+07,107.000000,6.300000,471.000000,11451.000000
75%,5.500000e+07,45272.000000,37.335721,1.462920e+08,121.000000,6.900000,1148.000000,45272.000000
max,3.800000e+08,417859.000000,875.581305,2.787965e+09,338.000000,8.500000,13752.000000,417859.000000

In [85]:
df.apply(lambda x: x['revenue'] - x['budget'], axis=1)

0       2550965087
1        661000000
2        635674609
3        834939099
4         24139100
           ...
4773       3124130
4788       5988000
4792         79000
4796        417760
4798       1820920
Length: 3229, dtype: int64

In [87]:
df['revenue'] - df['budget']

0       2550965087
1        661000000
2        635674609
3        834939099
4         24139100
           ...
4773       3124130
4788       5988000
4792         79000
4796        417760
4798       1820920
Length: 3229, dtype: int64

In [6]:
df['profit'] = df['revenue'] - df['budget']
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew,profit
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2550965087
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",661000000
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",635674609

In [10]:
len(df)

3229

In [8]:
df = df.sort_values('profit', ascending=False).reset_index(drop=True)
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew,profit
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2550965087
1,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,Released,Nothing on Earth could come between them.,Titanic,7.5,7562,597,Titanic,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de...",1645034188
2,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,Released,The park is open.,Jurassic World,6.5,8662,135397,Jurassic World,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...","[{""credit_id"": ""52fe4bf7c3a368484e1a0683"", ""de...",1363528810

In [9]:
df.groupby('original_language').mean(numeric_only=True)

,budget,id,popularity,revenue,runtime,vote_average,vote_count,movie_id,profit
original_language,,,,,,,,,
af,3.000000e+06,868.000000,2.504169,9.879971e+06,94.000000,6.900000,94.000000,868.000000,6.879971e+06
cn,1.984339e+07,89890.400000,13.019918,6.296073e+07,109.400000,6.600000,327.000000,89890.400000,4.311734e+07
da,1.510000e+07,44214.500000,25.788106,5.232305e+07,122.250000,6.900000,703.250000,44214.500000,3.722305e+07
de,2.019886e+07,12942.666667,21.885095,4.159554e+07,122.000000,7.255556,609.555556,12942.666667,2.139668e+07
en,4.166120e+07,44418.189877,29.478897,1.245451e+08,110.443262,6.287008,998.277885,44418.189877,8.288386e+07
es,1.027506e+07,33868.400000,22.382192,3.362737e+07,110.733333,6.926667,521.866667,33868.400000,2.335231e+07
fa,1.800000e+05,21334.000000,7.072118,9.000000e+05,89.000000,7.800000,112.000000,21334.000000,7.200000e+05
fr,1.786534e+07,34100.200000,14.171101,3.292465e+07,110.800000,6.824000,371.320000,34100.200000,1.505932e+07
he,2.000000e+06,8885.000000,14.082510,1.112585e+07,90.000000,7.800000,291.000000,8885.000000,9.125849e+06
hi,4.400000e+06,119319.571429,4.591614,2.010663e+07,157.285714,6.942857,81.000000,119319.571429,1.570663e+07
id,1.050000e+06,109003.500000,24.586253,2.274881e+06,108.000000,7.400000,632.500000,109003.500000,1.224881e+06
is,1.000000e+01,217708.000000,1.617943,1.100000e+01,85.000000,6.900000,26.000000,217708.000000,1.000000e+00
it,4.300005e+06,39572.166667,36.885970,7.068818e+06,127.500000,7.350000,876.666667,39572.166667,2.768814e+06
ja,1.563059e+07,49672.615385,30.411232,8.126636e+07,123.076923,7.192308,869.153846,49672.615385,6.563577e+07
ko,2.784000e+07,31157.800000,31.621601,5.102352e+07,115.000000,6.380000,1097.600000,31157.800000,2.318352e+07
nb,3.500000e+06,46146.000000,12.982319,4.159678e+06,103.000000,6.700000,583.000000,46146.000000,6.596780e+05
nl,1.250000e+07,12819.500000,9.460093,1.336156e+07,124.000000,7.000000,171.500000,12819.500000,8.615580e+05
no,8.000000e+05,14451.000000,11.205726,1.984662e+06,91.000000,6.100000,311.000000,14451.000000,1.184662e+06
pl,2.159280e+06,209274.000000,13.265432,1.070000e+07,80.000000,7.100000,260.000000,209274.000000,8.540720e+06
pt,3.100000e+06,632.000000,25.142824,1.811924e+07,121.500000,7.850000,970.000000,632.000000,1.501924e+07
ro,8.525100e+05,2009.000000,9.270133,1.185783e+06,113.000000,7.300000,156.000000,2009.000000,3.332730e+05
ru,1.628333e+07,57277.833333,6.613924,1.676217e+07,113.333333,6.033333,81.500000,57277.833333,4.788380e+05
te,4.000000e+07,256040.000000,16.254032,1.000000e+08,159.000000,7.500000,135.000000,256040.000000,6.000000e+07
th,7.250000e+06,12667.500000,10.423904,1.805112e+07,103.000000,6.400000,159.500000,12667.500000,1.080112e+07
vi,1.300000e+06,25784.000000,0.072066,6.390000e+05,135.000000,5.000000,1.000000,25784.000000,-6.610000e+05
xx,1.200000e+07,62204.000000,6.537986,5.526056e+07,100.000000,7.100000,109.000000,62204.000000,4.326056e+07
zh,3.751469e+07,104271.615385,13.102208,7.953696e+07,122.769231,6.338462,223.846154,104271.615385,4.202227e+07

In [17]:
df.to_csv(
    '../../../data/processed/lecture/tmdb_profit_sorted.csv',
    index=False
)

In [18]:
updated_df = pd.read_csv('../../../data/processed/lecture/tmdb_profit_sorted.csv')
updated_df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,status,tagline,title_movies,vote_average,vote_count,movie_id,title_credits,cast,crew,profit
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",2550965087
1,200000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.titanicmovie.com,597,"[{""id"": 2580, ""name"": ""shipwreck""}, {""id"": 298...",en,Titanic,"84 years later, a 101-year-old woman named Ros...",100.025899,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,Released,Nothing on Earth could come between them.,Titanic,7.5,7562,597,Titanic,"[{""cast_id"": 20, ""character"": ""Rose DeWitt Buk...","[{""credit_id"": ""52fe425ac3a36847f8017985"", ""de...",1645034188
2,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,Released,The park is open.,Jurassic World,6.5,8662,135397,Jurassic World,"[{""cast_id"": 10, ""character"": ""Owen Grady"", ""c...","[{""credit_id"": ""52fe4bf7c3a368484e1a0683"", ""de...",1363528810

In [16]:
len(updated_df)

3229

In [ ]:
up